version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
    depends_on:
      - db
    environment:
      DATABASE_URL: "sqlite+aiosqlite:///app/db.sqlite3"

  db:
    image: busybox
    container_name: sqlite_db
    volumes:
      - ./db.sqlite3:/data/db.sqlite3
    command: ["sh", "-c", "echo SQLite контейнер загружен"]
