version: "3.8"

services:
  app:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    command: >
      sh -c "python init_db.py && alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      DATABASE_URL: "sqlite+aiosqlite:///./db.sqlite3"

  db:
    image: busybox
    container_name: sqlite_db
    volumes:
      - ./db.sqlite3:/data/db.sqlite3
    command: ["sh", "-c", "echo SQLite контейнер загружен"]
