version: '3.8'
services:
  app:
    build: .
    container_name: fastapi_app
    volumes:
      - ./data:/app/data  # Монтируем директорию data
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////app/data/db.sqlite3  # Абсолютный путь к базе данных
    ports:
      - "8000:8000"