"""Remove roll_id and use id

Revision ID: fcf4a120d5ff
Revises: ce8ba4b22db6
Create Date: 2025-03-21 13:40:30.728653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf4a120d5ff'
down_revision: Union[str, None] = 'ce8ba4b22db6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rolls_roll_id', table_name='rolls')
    op.create_index(op.f('ix_rolls_id'), 'rolls', ['id'], unique=False)
    op.drop_column('rolls', 'roll_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rolls', sa.Column('roll_id', sa.INTEGER(), nullable=False))
    op.drop_index(op.f('ix_rolls_id'), table_name='rolls')
    op.create_index('ix_rolls_roll_id', 'rolls', ['roll_id'], unique=False)
    # ### end Alembic commands ###
